before_all do
  hours(start_timing: true)
end

lane :test do
  sleep(1)
end

lane :gem_release do
	sh "bundle install"
	sh "rake install"
	sh "rake release"
end

after_all do |lane|
  hours(measure_timing: true)
end