before_all do
  hours(start_timing: true)
end

lane :test do
  gym
  deliver
end

# Run `bundle exec fastlane gem_release` to release new version of 
lane :gem_release do
  sh "bundle install"
  sh "rake install"
  sh "rake release"
end

after_all do |lane|
  hours(measure_timing: true)
end
